// learnFromExamples (SPEC 5 flow A/A2): the end-to-end learn pipeline, from the two
// example files to a verified (or best-effort) rules file. Pure orchestration - every
// real decision (pre-flight, the fast path, masking, the payload, full verification)
// is already implemented elsewhere in this package; this module only sequences them
// exactly as SPEC 5 flow A describes, steps 1-6 (step 7, "show the rules map", and
// step 8, "saving", are UI/registry concerns outside the engine).
//
// Deliberately transport-agnostic: `callLearn`/`callRepair` are injected by the caller,
// so the SAME sequence runs whether they call the real `POST /api/learn` (the browser)
// or `apps/api/src/learn`'s `learn()`/`repairFromBrowser` in-process (the eval harness,
// SPEC 10). No DOM/Node APIs; no randomness beyond what a given `key` already carries.
import type { Format, LearnPayload, LearnResult, RepairProblem, Tier } from '@formatai/shared';
import { sniffDelimitedText } from '../io/detectFileSpec';
import { readWorkbook } from '../io/read';
import type { AnalysisProgress, AnalyzeOptions, PairAnalysis } from './analyze';
import { analyzePair } from './analyze';
import { fastPath } from './fastPath';
import { createMasker, unmaskRules, type Masker } from './mask';
import { buildPayload } from './payload';
import { preflight, type PreflightResult } from './preflight';
import { verifyAgainstExample, type VerifyResult } from './verify';

/** What `callLearn`/`callRepair` return - the shape of `apps/api/src/learn`'s
 * `LearnOutcome` (`learn()`/`repairFromBrowser()`), minus the `verified` flag this
 * module derives for itself from the browser's own full verification. Generic over
 * the call-record type so this engine package never has to import `@formatai/api`'s
 * `LlmCallRecord` (the wrong dependency direction - apps/api depends on the engine,
 * not the other way around): the caller's own record type just flows through. */
export interface LearnCallResult<Call = unknown> {
  /** Wire-decoded but NOT unmasked: exactly what the LLM produced (fake vocabulary
   * when masking is on). `learnFromExamples` unmasks it itself before verifying. */
  rules: LearnResult | null;
  problems: RepairProblem[];
  calls: Call[];
}

export interface LearnFromExamplesOptions<Call = unknown> {
  input: { bytes: Uint8Array; name: string };
  output: { bytes: Uint8Array; name: string };
  /** SPEC 7.2: on by default in the UI; passed explicitly here since the engine has no
   * default of its own. */
  masking: boolean;
  /**
   * The masking HMAC key (SPEC 7.2): "random per browser session and never leaves the
   * browser". Generated by the caller (`crypto.getRandomValues` in the browser; a
   * seeded key in the eval harness for determinism) - this module never generates
   * randomness. Required when `masking` is true.
   */
  key?: Uint8Array;
  tier: Tier;
  /** SPEC 8.12/A2: attach mode - the existing format this input must produce. */
  target?: Format;
  /** SPEC 6.4: "Try anyway" past a "rows couldn't be aligned" warning. Trying anyway
   * still counts as a learn, same as any other continued warn. */
  tryAnyway?: boolean;
  /** SPEC 5 A step 5: one learn action (however many calls it takes under the hood -
   * server repair rounds and escalation are `callLearn`'s own business, e.g.
   * `apps/api/src/learn`'s `learn()`). */
  callLearn: (payload: LearnPayload) => Promise<LearnCallResult<Call>>;
  /**
   * SPEC 5 A step 6 / 9.3: the one browser-triggered repair call, made only when the
   * browser's own full verification (not `callLearn`'s internal sample-run checks)
   * finds a mismatch. `previousRules` is passed back in the SAME (possibly masked)
   * vocabulary `callLearn` returned - never the unmasked copy this module verifies
   * with - because the API holds no masking key and can only recognize its own prior
   * fake words (SPEC 7.2/15: the key, and so the fake<->real map, never leaves the
   * browser).
   */
  callRepair?: (payload: LearnPayload, previousRules: LearnResult, problems: RepairProblem[]) => Promise<LearnCallResult<Call>>;
  onProgress?: (p: AnalysisProgress) => void;
}

export type LearnPath = 'blocked' | 'local' | 'llm';

/**
 * DECISION: SPEC 10's report needs per-stage shares ("share blocked, share fast path
 * ... verified on the first call, and verified after repair") that aren't fully
 * recoverable from `path`/`calls` alone (e.g. "verified on the first call" must mean
 * *before* any browser-triggered repair, which only this module knows about). This
 * summary is that bookkeeping, kept separate from `path` (which already answers
 * "blocked vs local vs llm") so callers - chiefly the eval runner - don't have to
 * re-derive it from `calls[].outcome` and guesswork.
 */
export interface LearnStages {
  preflight: PreflightResult['status'];
  fastPathTried: boolean;
  fastPathSucceeded: boolean;
  llmCalled: boolean;
  /** Full verification passed right after `callLearn` (+ unmask), before any
   * browser-triggered repair. Meaningless (always false) off the LLM path. */
  verifiedFirstCall: boolean;
  browserRepairUsed: boolean;
  /** Final verification result: after the browser-triggered repair when one was used,
   * otherwise the same as `verifiedFirstCall` (or the fast path's own verification). */
  verifiedAfterRepair: boolean;
}

export interface LearnFromExamplesResult<Call = unknown> {
  path: LearnPath;
  preflight: PreflightResult;
  /** UNMASKED (real) rules, ready to show/save/run - or null when blocked, or the LLM
   * never returned anything usable even after repair. */
  rules: LearnResult | null;
  /** Full-file verification (SPEC 5 A step 6) of `rules` - or null when blocked or
   * `rules` is null (nothing to verify). */
  verification: VerifyResult | null;
  assumptions: LearnResult['assumptions'];
  unsupported: LearnResult['unsupported'];
  calls: Call[];
  stages: LearnStages;
}

function emptyStages(status: PreflightResult['status']): LearnStages {
  return {
    preflight: status,
    fastPathTried: false,
    fastPathSucceeded: false,
    llmCalled: false,
    verifiedFirstCall: false,
    browserRepairUsed: false,
    verifiedAfterRepair: false,
  };
}

function blockedResult<Call>(pf: PreflightResult): LearnFromExamplesResult<Call> {
  return { path: 'blocked', preflight: pf, rules: null, verification: null, assumptions: [], unsupported: [], calls: [], stages: emptyStages(pf.status) };
}

/**
 * Runs SPEC 5 flow A/A2 end to end: read both files, analyze the pair, pre-flight,
 * the local fast path, the (optionally masked) payload, the learn call, unmasking,
 * full verification, and - when needed and offered - one browser-triggered repair.
 */
export async function learnFromExamples<Call = unknown>(opts: LearnFromExamplesOptions<Call>): Promise<LearnFromExamplesResult<Call>> {
  if (opts.masking && !opts.key) {
    throw new Error('learnFromExamples: masking is on but no key was given (SPEC 7.2: the key never leaves the browser, and this module never generates one)');
  }

  // ---- SPEC 5 A step 1: read both files (sniff delimited output bytes so
  // detectFileSpec can see quote: 'all' - SPEC 8.13) ----
  const inputWb = await readWorkbook(opts.input.bytes, opts.input.name);
  const outputWb = await readWorkbook(opts.output.bytes, opts.output.name);
  const outputSniff = outputWb.fileType === 'csv' || outputWb.fileType === 'txt' ? sniffDelimitedText(opts.output.bytes) : undefined;

  const analysisOpts: AnalyzeOptions = {};
  if (opts.onProgress) analysisOpts.onProgress = opts.onProgress;
  if (outputSniff) analysisOpts.outputSniff = outputSniff;
  // SPEC 8.12/A2: the output must already match the format, so its file spec is the
  // format's own, not re-detected from this particular example.
  if (opts.target) analysisOpts.outputFileSpec = opts.target.output.file;

  const analysis = analyzePair(inputWb, outputWb, analysisOpts);

  // ---- SPEC 5 A step 2 / 6.3-6.4: pre-flight ----
  const pf = preflight(analysis, opts.tier);
  if (pf.status === 'block') return blockedResult(pf);
  const rowsNotAligned = pf.issues.some((i) => i.code === 'rowsNotAligned');
  if (rowsNotAligned && !opts.tryAnyway) return blockedResult(pf);

  if (!analysis.ok) {
    // Unreachable: preflight() only returns a non-'block' status for a successful
    // analysis (see packages/engine/src/learn/preflight.ts).
    throw new Error('learnFromExamples: unreachable - pre-flight did not block a failed pair analysis');
  }

  const stages = emptyStages(pf.status);

  // ---- SPEC 5 A step 3 / 6.5: the local fast path. Skipped in attach mode: fastPath
  // has no format-lock awareness (SPEC 8.12 - output/sort/group must equal the
  // target's exactly), so an attached source always goes through the LLM, which is
  // told to copy `target` verbatim (LEARN_PROMPT "Adding a source to an existing
  // format"). ----
  if (!opts.target) {
    stages.fastPathTried = true;
    const fp = fastPath(analysis, pf);
    if ('rules' in fp) {
      stages.fastPathSucceeded = true;
      const verification = verifyAgainstExample(fp.rules, analysis);
      stages.verifiedFirstCall = verification.verified;
      stages.verifiedAfterRepair = verification.verified;
      return {
        path: 'local',
        preflight: pf,
        rules: fp.rules,
        verification,
        assumptions: fp.rules.assumptions,
        unsupported: fp.rules.unsupported,
        calls: [],
        stages,
      };
    }
  }

  // ---- SPEC 5 A step 4 / 7: the (optionally masked) payload ----
  const masker: Masker | undefined = opts.masking ? createMasker(opts.key!) : undefined;
  const { payload } = buildPayload(analysis, pf, { ...(masker ? { masker } : {}), ...(opts.target ? { target: opts.target } : {}) });

  // ---- SPEC 5 A step 5: the learn call ----
  stages.llmCalled = true;
  const learned = await opts.callLearn(payload);
  const calls: Call[] = [...learned.calls];

  if (!learned.rules) {
    return { path: 'llm', preflight: pf, rules: null, verification: null, assumptions: [], unsupported: [], calls, stages };
  }

  let maskedRules = learned.rules;
  let rules: LearnResult = masker ? unmaskRules(maskedRules, masker) : maskedRules;

  // ---- SPEC 5 A step 6 / 9.2 layer 8: full verification on the real, unmasked data ----
  let verification = verifyAgainstExample(rules, analysis, masker ? { masker } : {});
  stages.verifiedFirstCall = verification.verified;

  // ---- SPEC 5 A step 6 / 9.3: at most one browser-triggered repair ----
  if (!verification.verified && opts.callRepair) {
    stages.browserRepairUsed = true;
    const repaired = await opts.callRepair(payload, maskedRules, verification.repairProblems);
    calls.push(...repaired.calls);
    if (repaired.rules) {
      maskedRules = repaired.rules;
      rules = masker ? unmaskRules(maskedRules, masker) : maskedRules;
      verification = verifyAgainstExample(rules, analysis, masker ? { masker } : {});
    }
  }
  stages.verifiedAfterRepair = verification.verified;

  return { path: 'llm', preflight: pf, rules, verification, assumptions: rules.assumptions, unsupported: rules.unsupported, calls, stages };
}
