// learnFromExamples (SPEC 5 flow A/A2): the end-to-end learn pipeline, from the two
// example files to a verified (or best-effort) rules file. Pure orchestration - every
// real decision (pre-flight, the fast path, masking, the payload, full verification)
// is already implemented elsewhere in this package; this module only sequences them
// exactly as SPEC 5 flow A describes, steps 1-6 (step 7, "show the rules map", and
// step 8, "saving", are UI/registry concerns outside the engine).
//
// Deliberately transport-agnostic: `callLearn`/`callRepair` are injected by the caller,
// so the SAME sequence runs whether they call the real `POST /api/learn` (the browser)
// or `apps/api/src/learn`'s `learn()`/`repairFromBrowser` in-process (the eval harness,
// SPEC 10). No DOM/Node APIs; no randomness beyond what a given `key` already carries.
import type { AiStepPartCode, Format, LearnPayload, LearnResult, RepairProblem, Tier } from '@formatai/shared';
import { sniffDelimitedText } from '../io/detectFileSpec';
import { readWorkbook } from '../io/read';
import type { AnalysisProgress, AnalyzeOptions, PairAnalysis } from './analyze';
import { analyzePair } from './analyze';
import { checkFixedLock, type FixedProblem } from '../registry/checkFixedLock';
import { completionProduced, isCompletable, type CompleteOptions } from './complete';
import { fastPath } from './fastPath';
import { createMasker, unmaskRules, type Masker } from './mask';
import { partialRules, type PartialRulesResult } from './partial';
import { preflight, type PreflightResult } from './preflight';
import { aiReadiness, type AiReadiness } from './readiness';
import { verifyAgainstExample, type VerifyResult } from './verify';

/** What `callLearn`/`callRepair` return - the shape of `apps/api/src/learn`'s
 * `LearnOutcome` (`learn()`/`repairFromBrowser()`), minus the `verified` flag this
 * module derives for itself from the browser's own full verification. Generic over
 * the call-record type so this engine package never has to import `@formatai/api`'s
 * `LlmCallRecord` (the wrong dependency direction - apps/api depends on the engine,
 * not the other way around): the caller's own record type just flows through. */
export interface LearnCallResult<Call = unknown> {
  /** Wire-decoded but NOT unmasked: exactly what the LLM produced (fake vocabulary
   * when masking is on). `learnFromExamples` unmasks it itself before verifying. */
  rules: LearnResult | null;
  problems: RepairProblem[];
  calls: Call[];
}

export interface LearnFromExamplesOptions<Call = unknown> {
  input: { bytes: Uint8Array; name: string };
  output: { bytes: Uint8Array; name: string };
  /** SPEC 7.2: on by default in the UI; passed explicitly here since the engine has no
   * default of its own. */
  masking: boolean;
  /**
   * The masking HMAC key (SPEC 7.2): "random per browser session and never leaves the
   * browser". Generated by the caller (`crypto.getRandomValues` in the browser; a
   * seeded key in the eval harness for determinism) - this module never generates
   * randomness. Required when `masking` is true.
   */
  key?: Uint8Array;
  tier: Tier;
  /** SPEC 8.12/A2: attach mode - the existing format this input must produce. */
  target?: Format;
  /** SPEC 6.4: "Try anyway" past a "rows couldn't be aligned" warning. Trying anyway
   * still counts as a learn once it reaches the AI step, same as any other continued warn. It never
   * gets past the AI readiness gate (SPEC 21 v5 item 4): with no matched rows at all there is nothing
   * to learn from (`path: 'notReady'`). */
  tryAnyway?: boolean;
  /**
   * SPEC 21 v5 item 1: whether this caller may use the AI step at all. 'notAllowed' (a user who isn't
   * signed in) never reaches the LLM: when the fast path can't finish, the learn returns the local
   * partial result (`path: 'partial'`) instead, with the columns that need the AI step listed. Default
   * 'allowed' (the existing behavior). `callLearn` is never called when 'notAllowed'.
   */
  ai?: 'allowed' | 'notAllowed';
  /**
   * Completion mode (LEARN_PROMPT "Completing a partial rules file"): the user already has part of the rules
   * (`fixedRules`, exactly as they are on screen) and the AI step only produces what is listed - output
   * `columns` and layout `parts`. The fast path and the local partial result are skipped (the caller decided the AI
   * step is wanted), the payload carries `complete`, and the answer must pass the fixed lock (`checkFixedLock`) as
   * well as the full verification - see `LearnFromExamplesResult.completion`. Not combined with `target`.
   */
  complete?: CompleteOptions;
  /** SPEC 5 A step 5: one learn action (however many calls it takes under the hood -
   * server repair rounds and escalation are `callLearn`'s own business, e.g.
   * `apps/api/src/learn`'s `learn()`). */
  callLearn: (payload: LearnPayload) => Promise<LearnCallResult<Call>>;
  /**
   * SPEC 5 A step 6 / 9.3: the one browser-triggered repair call, made only when the
   * browser's own full verification (not `callLearn`'s internal sample-run checks)
   * finds a mismatch. `previousRules` is passed back in the SAME (possibly masked)
   * vocabulary `callLearn` returned - never the unmasked copy this module verifies
   * with - because the API holds no masking key and can only recognize its own prior
   * fake words (SPEC 7.2/15: the key, and so the fake<->real map, never leaves the
   * browser).
   */
  callRepair?: (payload: LearnPayload, previousRules: LearnResult, problems: RepairProblem[]) => Promise<LearnCallResult<Call>>;
  onProgress?: (p: AnalysisProgress) => void;
  /**
   * Called once with the successful pair analysis, before pre-flight. The web worker keeps it
   * in memory so the rules editor's live check (SPEC 8.11) can re-run the rules on the example
   * without reading the two files again. Purely an observer: it cannot change the flow.
   */
  onAnalysis?: (analysis: PairAnalysis) => void;
}

/**
 * blocked: pre-flight (SPEC 6.3) stopped it.  local: the strict fast path finished it, no LLM.
 * llm: the AI step ran.  partial (v5): the local partial result - see `LearnFromExamplesResult.partial`.
 * notReady (v5): the AI readiness gate stopped the AI step - see `readiness`; nothing was consumed.
 */
export type LearnPath = 'blocked' | 'local' | 'llm' | 'partial' | 'notReady';

/**
 * DECISION: SPEC 10's report needs per-stage shares ("share blocked, share fast path
 * ... verified on the first call, and verified after repair") that aren't fully
 * recoverable from `path`/`calls` alone (e.g. "verified on the first call" must mean
 * *before* any browser-triggered repair, which only this module knows about). This
 * summary is that bookkeeping, kept separate from `path` (which already answers
 * "blocked vs local vs llm") so callers - chiefly the eval runner - don't have to
 * re-derive it from `calls[].outcome` and guesswork.
 */
export interface LearnStages {
  preflight: PreflightResult['status'];
  fastPathTried: boolean;
  fastPathSucceeded: boolean;
  llmCalled: boolean;
  /** Full verification passed right after `callLearn` (+ unmask), before any
   * browser-triggered repair. Meaningless (always false) off the LLM path. */
  verifiedFirstCall: boolean;
  browserRepairUsed: boolean;
  /** Final verification result: after the browser-triggered repair when one was used,
   * otherwise the same as `verifiedFirstCall` (or the fast path's own verification). */
  verifiedAfterRepair: boolean;
  /** v5: the AI readiness gate ran (the fast path did not finish the learn). */
  readinessChecked?: boolean;
  /** v5: the gate stopped the AI step with a block (`path: 'notReady'`). */
  readinessBlocked?: boolean;
  /** v5: the local partial result was built and returned (`path: 'partial'`). */
  partialBuilt?: boolean;
}

/** v5 item 1: what the local partial result holds and why it was returned. */
export interface PartialInfo {
  /** The caller may not use the AI step (sign in to finish). It is the only reason: a result is never finished locally because the
   * remaining columns "look external" - the AI step tries every column code couldn't explain (SPEC 6.4, 21 v7 note). */
  reason: 'aiNotAllowed';
  /** Headers of the output columns code built (and `verification` counts). */
  solved: string[];
  /** Headers of EVERY output column that needs the AI step: the ones with a dependency or composition code couldn't turn into a rule,
   * and the ones it found no relation to the input for at all (`external`). */
  needsAi: string[];
  /** The subset of `needsAi` whose values code could not find in the input file: they "may come from another source" (wording only). */
  external: string[];
  /** Output column positions of `solved`. */
  solvedColumns: number[];
  /** What besides columns still needs the AI step (rows that change shape, dropped rows, sort, groups, ...). */
  needsAiParts: AiStepPartCode[];
}

export interface LearnFromExamplesResult<Call = unknown> {
  path: LearnPath;
  preflight: PreflightResult;
  /** UNMASKED (real) rules, ready to show/save/run - or null when blocked, or the LLM
   * never returned anything usable even after repair. */
  rules: LearnResult | null;
  /** Full-file verification (SPEC 5 A step 6) of `rules` - or null when blocked or
   * `rules` is null (nothing to verify). */
  verification: VerifyResult | null;
  assumptions: LearnResult['assumptions'];
  unsupported: LearnResult['unsupported'];
  calls: Call[];
  stages: LearnStages;
  /** path 'partial': see `PartialInfo`. `rules` are the partial rules; `verification` counts the solved columns only. */
  partial?: PartialInfo;
  /** The AI readiness verdict, when the gate ran (paths 'notReady', 'partial' and 'llm'). Issues carry codes and
   * params for `aiReadinessMessages`; the payload the check built is not included. */
  readiness?: AiReadiness;
  /**
   * Completion mode, path 'llm' with rules: what was asked, and the fixed lock's findings on the (unmasked) answer against the
   * real fixed rules. The answer may replace the user's rules only when `fixedProblems` is empty AND `matches`.
   */
  completion?: {
    columns: number[];
    parts: AiStepPartCode[];
    fixedProblems: FixedProblem[];
    /**
     * The answer matches the example as far as the AI step is responsible for it: every cell of a column it produced matches, and it made
     * nothing worse anywhere else - a difference the user's own rules already had (an edit that departs from the example on purpose, a
     * layout part still missing) is not counted against it, and neither is a column that still has no rule (the AI step may report a
     * listed column as unsupported; it is left empty, and the editor says "needs your input").
     */
    matches: boolean;
    /** What the answer produced of what was asked: listed columns that got a rule, listed parts it built. Nothing produced is no completion. */
    produced: { columns: number; parts: number };
  };
}

/** Like the diff problems (LEARN_PROMPT §4: "At most 10 diff problems are sent"), a repair call needs enough fixed-lock findings to fix the pattern, not all of them. */
const MAX_FIXED_PROBLEMS = 10;

function emptyStages(status: PreflightResult['status']): LearnStages {
  return {
    preflight: status,
    fastPathTried: false,
    fastPathSucceeded: false,
    llmCalled: false,
    verifiedFirstCall: false,
    browserRepairUsed: false,
    verifiedAfterRepair: false,
    readinessChecked: false,
    readinessBlocked: false,
    partialBuilt: false,
  };
}

function blockedResult<Call>(pf: PreflightResult): LearnFromExamplesResult<Call> {
  return { path: 'blocked', preflight: pf, rules: null, verification: null, assumptions: [], unsupported: [], calls: [], stages: emptyStages(pf.status) };
}

/**
 * Runs SPEC 5 flow A/A2 end to end: read both files, analyze the pair, pre-flight,
 * the local fast path, the AI readiness gate (v5: which also builds the (optionally masked) payload, and
 * decides whether the AI step runs at all - see `ai`, `partial` and `readiness`), the learn call,
 * unmasking, full verification, and - when needed and offered - one browser-triggered repair.
 */
export async function learnFromExamples<Call = unknown>(opts: LearnFromExamplesOptions<Call>): Promise<LearnFromExamplesResult<Call>> {
  if (opts.masking && !opts.key) {
    throw new Error('learnFromExamples: masking is on but no key was given (SPEC 7.2: the key never leaves the browser, and this module never generates one)');
  }
  if (opts.complete) {
    if (opts.target) throw new Error('learnFromExamples: completion mode and attach mode (target) cannot be combined');
    if (opts.ai === 'notAllowed') throw new Error('learnFromExamples: completion mode is the AI step, but the AI step is not allowed');
    if (!isCompletable(opts.complete.fixedRules)) throw new Error('learnFromExamples: complete.fixedRules is not a valid rules file');
  }

  // ---- SPEC 5 A step 1: read both files (sniff delimited output bytes so
  // detectFileSpec can see quote: 'all' - SPEC 8.13) ----
  const inputWb = await readWorkbook(opts.input.bytes, opts.input.name);
  const outputWb = await readWorkbook(opts.output.bytes, opts.output.name);
  const outputSniff = outputWb.fileType === 'csv' || outputWb.fileType === 'txt' ? sniffDelimitedText(opts.output.bytes) : undefined;

  const analysisOpts: AnalyzeOptions = {};
  if (opts.onProgress) analysisOpts.onProgress = opts.onProgress;
  if (outputSniff) analysisOpts.outputSniff = outputSniff;
  // SPEC 8.12/A2: the output must already match the format, so its file spec is the
  // format's own, not re-detected from this particular example.
  if (opts.target) analysisOpts.outputFileSpec = opts.target.output.file;

  const analysis = analyzePair(inputWb, outputWb, analysisOpts);
  if (analysis.ok) opts.onAnalysis?.(analysis);

  // ---- SPEC 5 A step 2 / 6.3-6.4: pre-flight ----
  const pf = preflight(analysis, opts.tier);
  if (pf.status === 'block') return blockedResult(pf);
  const rowsNotAligned = pf.issues.some((i) => i.code === 'rowsNotAligned');
  if (rowsNotAligned && !opts.tryAnyway) return blockedResult(pf);

  if (!analysis.ok) {
    // Unreachable: preflight() only returns a non-'block' status for a successful
    // analysis (see packages/engine/src/learn/preflight.ts).
    throw new Error('learnFromExamples: unreachable - pre-flight did not block a failed pair analysis');
  }

  const stages = emptyStages(pf.status);

  // ---- SPEC 5 A step 3 / 6.5: the local fast path. Skipped in attach mode: fastPath
  // has no format-lock awareness (SPEC 8.12 - output/sort/group must equal the
  // target's exactly), so an attached source always goes through the LLM, which is
  // told to copy `target` verbatim (LEARN_PROMPT "Adding a source to an existing
  // format"). ----
  if (!opts.target && !opts.complete) {
    stages.fastPathTried = true;
    const fp = fastPath(analysis, pf);
    if ('rules' in fp) {
      stages.fastPathSucceeded = true;
      const verification = verifyAgainstExample(fp.rules, analysis);
      stages.verifiedFirstCall = verification.verified;
      stages.verifiedAfterRepair = verification.verified;
      return {
        path: 'local',
        preflight: pf,
        rules: fp.rules,
        verification,
        assumptions: fp.rules.assumptions,
        unsupported: fp.rules.unsupported,
        calls: [],
        stages,
      };
    }
  }

  // ---- SPEC 21 v5 item 4: the AI readiness gate, before any payload or LLM call. It also builds the
  // (optionally masked, SPEC 7.2) payload, which the learn call below then uses as it is. ----
  const ai = opts.ai ?? 'allowed';
  const masker: Masker | undefined = opts.masking ? createMasker(opts.key!) : undefined;
  // (The local partial result is only for a caller that may not use the AI step.)
  const partial = opts.complete || ai !== 'notAllowed' ? null : localPartial(analysis, pf);
  const readiness = aiReadiness(analysis, pf, {
    ...(masker ? { masker } : {}),
    ...(opts.target ? { target: opts.target } : {}),
    ...(opts.complete ? { complete: opts.complete } : {}),
  });
  stages.readinessChecked = true;
  const shownReadiness: AiReadiness = readiness.ready ? { ready: true } : readiness;

  // A block: the AI step can't succeed. Signed-out callers still get the local result unless it has no
  // example pairs at all (then signing in wouldn't help either).
  if (!readiness.ready) {
    const noPairs = readiness.issues.some((i) => i.code === 'noRowsMatched');
    if (partial && !noPairs) return partialResult(analysis, pf, partial, shownReadiness, stages);
    stages.readinessBlocked = true;
    return { path: 'notReady', preflight: pf, rules: null, verification: null, assumptions: [], unsupported: [], calls: [], stages, readiness: shownReadiness };
  }

  // The AI step isn't available to this caller: the local partial result is what they get (SPEC 21 v5 item 1).
  if (ai === 'notAllowed') {
    if (partial) return partialResult(analysis, pf, partial, shownReadiness, stages);
    return blockedResult(pf);
  }

  // ---- SPEC 5 A step 4 / 7: the payload (built by the gate) ----
  const payload: LearnPayload = readiness.built!.payload;

  // ---- SPEC 5 A step 5: the learn call ----
  stages.llmCalled = true;
  const learned = await opts.callLearn(payload);
  const calls: Call[] = [...learned.calls];

  if (!learned.rules) {
    return { path: 'llm', preflight: pf, rules: null, verification: null, assumptions: [], unsupported: [], calls, stages, readiness: shownReadiness };
  }

  let maskedRules = learned.rules;
  let rules: LearnResult = masker ? unmaskRules(maskedRules, masker) : maskedRules;

  // ---- SPEC 5 A step 6 / 9.2 layer 8: full verification on the real, unmasked data ----
  let verification = verifyAgainstExample(rules, analysis, masker ? { masker } : {});
  // Completion mode: the answer must also still contain the user's rules, unchanged (the API checked this on the masked
  // copies; this is the same check on the real ones, before anything replaces what the user has).
  const fixedLock = (r: LearnResult): FixedProblem[] => (opts.complete ? checkFixedLock(r, opts.complete.fixedRules, { columns: opts.complete.columns, parts: opts.complete.parts }) : []);
  let fixedProblems = fixedLock(rules);
  // What "the answer is good" means: a plain learn - the full verification; completion - that too, but a column with no rule does not count.
  // DECISION: in completion mode "matches the example" is relative to the user's own rules - the AI step answers for the columns it produced
  // (every cell must match) and must not make anything else worse; a difference the fixed rules already had (an edit that departs from the
  // example on purpose, a part still missing) is not its fault. Against the raw example no edit of a header or a value could ever pass.
  // What the user's own rules already differ by, against the example:
  const before = opts.complete ? verifyAgainstExample(opts.complete.fixedRules, analysis) : null;
  const cellKey = (m: { exampleRow: number; column: string }): string => `${m.exampleRow}\u0000${m.column}`;
  const matchesExample = (v: VerifyResult, r: LearnResult): boolean => {
    if (!opts.complete || !before) return v.verified;
    if (v.verified) return true;
    const noRule = new Set(r.output.columns.filter((c) => c.from === null).map((c) => c.header));
    const produced = new Set(opts.complete.columns.map((i) => r.output.columns[i]).filter((c) => c !== undefined && c.from !== null).map((c) => c!.header));
    const hadCell = new Set(before.mismatches.map(cellKey));
    const hadLayout = new Set(before.layoutIssues.map((i) => `${i.code}\u0000${i.message}`));
    const worse =
      v.mismatches.some((m) => !noRule.has(m.column) && (produced.has(m.column) || !hadCell.has(cellKey(m)))) ||
      v.layoutIssues.some((i) => !hadLayout.has(`${i.code}\u0000${i.message}`));
    return !worse;
  };
  const passes = (v: VerifyResult, r: LearnResult, lock: readonly FixedProblem[]): boolean => lock.length === 0 && matchesExample(v, r);
  stages.verifiedFirstCall = passes(verification, rules, fixedProblems);

  // ---- SPEC 5 A step 6 / 9.3: at most one browser-triggered repair ----
  if (!passes(verification, rules, fixedProblems) && opts.callRepair) {
    stages.browserRepairUsed = true;
    const problems: RepairProblem[] = [...fixedProblems.slice(0, MAX_FIXED_PROBLEMS), ...verification.repairProblems];
    const repaired = await opts.callRepair(payload, maskedRules, problems);
    calls.push(...repaired.calls);
    if (repaired.rules) {
      maskedRules = repaired.rules;
      rules = masker ? unmaskRules(maskedRules, masker) : maskedRules;
      verification = verifyAgainstExample(rules, analysis, masker ? { masker } : {});
      fixedProblems = fixedLock(rules);
    }
  }
  stages.verifiedAfterRepair = passes(verification, rules, fixedProblems);

  return {
    path: 'llm',
    preflight: pf,
    rules,
    verification,
    assumptions: rules.assumptions,
    unsupported: rules.unsupported,
    calls,
    stages,
    readiness: shownReadiness,
    ...(opts.complete ? { completion: { columns: [...opts.complete.columns], parts: [...opts.complete.parts], fixedProblems, matches: matchesExample(verification, rules), produced: completionProduced(rules, opts.complete.fixedRules, opts.complete) } } : {}),
  };
}

/** The local partial result, or null when there is none. It is a preview built from what code already knows, so a
 * problem in building it must never take down a learn that would otherwise reach the AI step. */
function localPartial(analysis: PairAnalysis, pf: PreflightResult): PartialRulesResult | null {
  try {
    const p = partialRules(analysis, pf);
    return 'reason' in p ? null : p;
  } catch {
    return null;
  }
}

/** The local partial result (SPEC 21 v5 item 1): built rules for what code explained, checked against the
 * example on those columns only. */
function partialResult<Call>(
  analysis: PairAnalysis,
  pf: PreflightResult,
  partial: PartialRulesResult,
  readiness: AiReadiness,
  stages: LearnStages,
): LearnFromExamplesResult<Call> {
  stages.partialBuilt = true;
  const verification = verifyAgainstExample(partial.rules, analysis, { onlyColumns: partial.solvedColumns });
  return {
    path: 'partial',
    preflight: pf,
    rules: partial.rules,
    verification,
    assumptions: partial.assumptions,
    unsupported: partial.rules.unsupported,
    calls: [],
    stages,
    partial: {
      reason: 'aiNotAllowed',
      solved: partial.solved,
      needsAi: partial.needsAi,
      external: partial.external,
      solvedColumns: partial.solvedColumns,
      needsAiParts: partial.needsAiParts,
    },
    readiness,
  };
}
