// English sentences of the rules map (SPEC 8.11, tone per SPEC 16.3: plain words, "format" not
// "schema", "check" not "validate"). This file defines the phrase keys; `phrases.he.ts` must
// provide every one of them (its type is `Record<PhraseKey, string>`).
//
// `{name}` marks where a column name, value or sub-sentence goes. Words that have a singular
// form carry a `.one` / `.other` pair; `tn()` picks one from a count.
import { joinWith, txt } from './parts';
import type { Joiners } from './phrases';
import type { Part } from './types';

export const en = {
  'section.rows': 'Rows',
  'section.columns': 'Columns',
  'section.layout': 'Layout',
  'section.checks': 'Checks',
  'section.functions': 'Functions and tables',

  'word.unnamed': '(no name)',
  'word.true': 'TRUE',
  'word.false': 'FALSE',
  'word.empty': 'empty',
  'word.space': 'a space',
  more: '… and {n} more',

  // Reading the input
  'input.sheetName': 'Read the sheet {name}',
  'input.sheetIndex': 'Read sheet number {n}',
  'input.headerRow': 'The header is on row {n}',
  'input.stopAt': 'Stop reading at the first row that starts with {values}',

  // Rows
  'filter.keep': 'Keep rows where {cond}',
  'cond.eq': '{a} is {b}',
  'cond.ne': '{a} is not {b}',
  'cond.gt': '{a} is greater than {b}',
  'cond.gte': '{a} is at least {b}',
  'cond.lt': '{a} is less than {b}',
  'cond.lte': '{a} is at most {b}',
  'cond.isEmpty': '{a} is empty',
  'cond.notEmpty': '{a} is not empty',
  'cond.oneOf': '{a} is one of {values}',
  'cond.notOneOf': '{a} is not one of {values}',
  'cond.startsWith': '{a} starts with {b}',
  'cond.endsWith': '{a} ends with {b}',
  'cond.contains': '{a} contains {b}',
  'cond.not': 'not ({c})',
  'cond.andJoin': ' and ',
  'cond.orJoin': ' or ',

  'dedupe.same.one': 'Rows with the same {keys}',
  'dedupe.same.other': 'Rows with the same {keys}',
  'dedupe.identical': 'Rows that are identical in every column',
  'dedupe.removeFirst': '{same}: keep the first, remove the others',
  'dedupe.removeLast': '{same}: keep the last, remove the earlier ones',
  'dedupe.flagFirst': '{same}: keep the first, flag the others as duplicates',
  'dedupe.flagLast': '{same}: keep the last, flag the earlier ones as duplicates',

  'expand.columnsToRows':
    'Turn {cols} into separate rows: the column name goes in {label} and its value in {value}',
  'expand.skipEmptyCells': 'empty cells are skipped',
  'expand.customLabels': 'using the labels you set for the column names',
  'expand.splitCell': 'Split {col} at {sep} into separate rows: each part goes in {part}',
  'expand.splitIndex': 'the part number goes in {idx}',
  'expand.splitCount': 'the number of parts goes in {cnt}',
  'expand.trimmed': 'spaces around each part are removed',
  'expand.skipEmptyParts': 'empty parts are skipped',
  'expand.fan': 'Every row becomes {count} ({rows})',
  'expand.fanRow': 'row {n}: {cells}',
  'expand.fanCell': '{col} = {expr}',
  'made.label': 'the column name',
  'made.value': 'the value',
  'made.part': 'the part',
  'made.index': 'the part number',
  'made.count': 'the number of parts',
  'expand.labelValue': 'the name of the column the value came from ({cols})',
  'expand.valueValue': 'the value from that column',
  'expand.partValue': 'each part of {col}',
  'expand.indexValue': 'the part number',
  'expand.countValue': 'the number of parts',
  'expand.fanValue': 'in new row {n}: {expr}',

  // Columns
  'col.emptyNeedsInput': 'left empty (needs your input)',
  'col.missing': "a column that isn't there",
  'col.leftEmpty': 'left empty',
  'col.fixed': 'fixed value {v}',
  'col.translated': 'translated from {src} ({count}; {missing})',
  'col.thenTranslated': 'then translated ({count}; {missing})',
  'translate.missingFlag': 'new values are flagged',
  'translate.missingKeep': 'new values stay as they are',
  'mod.padDigits': 'padded to {n} digits',
  'mod.padChars': 'padded to {n} characters with {c}',
  'mod.dateShown': 'shown as {f}',
  'mod.roundedWhole': 'rounded to a whole number',
  'mod.roundedNearest': 'rounded to the nearest {step}',
  'mod.trimmed': 'with extra spaces removed',
  'mod.upper': 'in capital letters',
  'mod.lower': 'in lower case',
  'mod.floor': 'rounded down to a whole number',
  'mod.ceil': 'rounded up to a whole number',
  'mod.asNumber': 'read as a number',
  'mod.asText': 'as text',
  'mod.asTextFormat': 'as text formatted {f}',
  'agg.sum': 'summed for each {by}',
  'agg.count': 'counted for each {by}',
  'agg.min': 'the lowest value for each {by}',
  'agg.max': 'the highest value for each {by}',
  'agg.average': 'averaged for each {by}',
  'agg.first': 'the first value for each {by}',
  'agg.last': 'the last value for each {by}',

  'expr.abs': 'the absolute value of {x}',
  'expr.charsFrom': '{n} characters of {x}, starting at position {p}',
  'expr.charsFromEnd': '{n} characters of {x}, starting {p} from the end',
  'expr.joinedSep': '{first} joined with {rest}, separated by {sep}',
  'expr.joined': '{first} joined with {rest}',
  'expr.textOf': 'text made of {items}',
  'expr.lookup': '{ret} from the table {table}, found by {key}',
  'expr.lookupMissing.flag': '(missing keys are flagged)',
  'expr.lookupMissing.empty': '(missing keys are left empty)',
  'expr.lookupMissing.keep': '(missing keys are kept as they are)',
  'expr.if': '{then} if {cond}, otherwise {else}',
  'expr.case': '{then} if {when}',
  'expr.otherwise': 'otherwise {else}',
  'expr.coalesce': 'the first non-empty of {items}',
  'expr.datePart.year': 'the year of {x}',
  'expr.datePart.month': 'the month of {x}',
  'expr.datePart.day': 'the day of {x}',
  'expr.dateFormat': '{x} written as {f}',
  'expr.datePlus': '{x} plus {amount}',
  'expr.dateMinus': '{x} minus {amount}',
  'expr.dateDiff': 'the number of {unit} between {a} and {b}',
  'unit.days': 'days',
  'unit.months': 'months',
  'unit.years': 'years',
  'expr.endOfMonth': 'the last day of the month of {x}',
  'expr.replace': '{x} with {find} replaced by {with}',
  'expr.remove': '{x} with {find} removed',
  'expr.split': 'part {n} of {x}, split at {sep}',
  'expr.splitLast': 'the last part of {x}, split at {sep}',
  'expr.splitFromEnd': 'part {n} from the end of {x}, split at {sep}',
  'expr.length': 'the number of characters in {x}',
  'expr.min': 'the smallest of {items}',
  'expr.max': 'the largest of {items}',
  'expr.mod': 'the remainder when {a} is divided by {b}',
  'expr.condValue': 'yes if {cond}, otherwise no',
  'expr.custom': 'a custom calculation',

  // Layout
  'title.text': 'Title: {text}',
  'title.blank': 'A blank row',
  'title.bold': 'in bold',
  'title.max.month': 'the month of the latest {col} ({f})',
  'title.max.year': 'the year of the latest {col} ({f})',
  'title.max.date': 'the latest {col} ({f})',
  'title.min.month': 'the month of the earliest {col} ({f})',
  'title.min.year': 'the year of the earliest {col} ({f})',
  'title.min.date': 'the earliest {col} ({f})',
  'sort.by': 'Sorted by {keys}',
  'sort.then': ', then ',
  'sort.desc.date': '(newest first)',
  'sort.desc.number': '(largest first)',
  'sort.desc.text': '(Z to A)',
  'sort.desc.plain': '(descending)',
  'group.detail': 'Group rows by {by} (every row is shown)',
  'group.summaryOnly': 'One row for each {by}; the detail rows are not shown',
  'summary.afterGroup': 'After each {by}: {row}',
  'summary.atEnd': 'At the end: {row}',
  'summary.row': 'a row {label} with {cells}',
  'summary.rowNoLabel': 'a row with {cells}',
  'summary.rowOnlyLabel': 'a row {label}',
  'summary.rowEmpty': 'an empty summary row',
  'summary.bold': 'in bold',
  'summary.sum': 'the sum of {col}',
  'summary.count': 'the count of {col}',
  'summary.min': 'the minimum of {col}',
  'summary.max': 'the maximum of {col}',
  'summary.average': 'the average of {col}',
  'summary.first': 'the first value of {col}',
  'summary.last': 'the last value of {col}',
  'file.xlsx': 'Excel file, sheet {sheet}, {dir}',
  'dir.rtl': 'right-to-left',
  'dir.ltr': 'left-to-right',
  'file.kind.comma': 'Comma-separated text file (CSV)',
  'file.kind.tab': 'Tab-separated text file',
  'file.kind.semicolon': 'Semicolon-separated text file',
  'file.kind.pipe': 'Pipe-separated text file',
  'file.header': 'with a header row',
  'file.noHeader': 'no header row',
  'file.enc.utf8bom': 'UTF-8 with BOM',
  'file.enc.utf8': 'UTF-8',
  'file.enc.windows1255': 'Windows-1255',
  'file.quote.all': 'every value in quotes',
  'file.quote.none': 'no quotes',

  // Checks
  'check.line': 'Check: {rule} ({severity})',
  'check.severity.flag': 'flag',
  'check.severity.block': 'leave out',
  'check.required': '{col} is not empty',
  'check.israeliId': '{col} is a valid Israeli ID number',
  'check.range.both': '{col} is between {min} and {max}',
  'check.range.min': '{col} is at least {min}',
  'check.range.max': '{col} is at most {max}',
  'check.range.none': '{col} is a number',
  'check.oneOf': '{col} is one of {values}',
  'check.unique': '{col} has no repeated values',
  'check.dateRange': '{col} is a date from {from} to {to}',

  // Functions and tables
  'table.line': 'Table {name}: {count}, look up by {key} to get {cols}',
  'table.single': 'Table {name}: {count} of {key}',

  // Why a line has the status it has
  'reason.noSource': "Nothing fills this column yet. Choose how it's made.",
  'reason.dangling': "This column uses something that isn't in your input file.",
  'reason.rowsDiffer': "The number of rows doesn't match your example.",
  'reason.layoutDiffers': "This part doesn't fully match your example.",
  'reason.edited': 'You changed this.',
  'reason.textFileLayout':
    "Text files usually don't have title, blank or summary rows. Check that the system reading this file accepts them.",

  // Words with a singular form (see `tn`)
  'values.one': '1 value',
  'values.other': '{n} values',
  'rows.one': '1 row',
  'rows.other': '{n} rows',
  'entries.one': '1 entry',
  'entries.other': '{n} entries',
  'days.one': '1 day',
  'days.other': '{n} days',
  'months.one': '1 month',
  'months.other': '{n} months',
  'years.one': '1 year',
  'years.other': '{n} years',
  'decimals.one': 'rounded to 1 decimal',
  'decimals.other': 'rounded to {n} decimals',
  'expr.firstChars.one': 'the first character of {x}',
  'expr.firstChars.other': 'the first {n} characters of {x}',
  'expr.lastChars.one': 'the last character of {x}',
  'expr.lastChars.other': 'the last {n} characters of {x}',
  'blank.after.one': 'Leave 1 blank row after each {by}',
  'blank.after.other': 'Leave {n} blank rows after each {by}',
  'check.length.one': '{col} is exactly 1 character long',
  'check.length.other': '{col} is exactly {n} characters long',
  'reason.mismatch.one': 'Differs from your example in {n} of {total} row.',
  'reason.mismatch.other': 'Differs from your example in {n} of {total} rows.',
} as const satisfies Record<string, string>;

function joinList(items: readonly (readonly Part[])[], word: string): Part[] {
  if (items.length <= 1) return joinWith(items, '');
  const head = joinWith(items.slice(0, -1), ', ');
  const last = items[items.length - 1] ?? [];
  return joinWith([head, [txt(` ${word} `)], last], '');
}

export const enJoiners: Joiners = {
  and: (items) => joinList(items, 'and'),
  or: (items) => joinList(items, 'or'),
};
