// Hebrew sentences of the rules map. Same keys and placeholders as `phrases.en.ts`.
// Style: noun forms ("שמירת שורות…", "מיון לפי…") so no sentence depends on the gender of a
// column name, and nothing is glued to a placeholder except the usual hyphen before a value
// ("ל-0", "מ-'מבוטל'"), which is how Hebrew is written next to Latin text and numbers.
import { joinWith, txt } from './parts';
import type { PhraseKey, Joiners } from './phrases';
import type { Part } from './types';

export const he: Record<PhraseKey, string> = {
  'section.rows': 'שורות',
  'section.columns': 'עמודות',
  'section.layout': 'פריסה',
  'section.checks': 'בדיקות',
  'section.functions': 'פונקציות וטבלאות',

  'word.unnamed': '(ללא שם)',
  'word.true': 'אמת',
  'word.false': 'שקר',
  'word.empty': 'ריק',
  'word.space': 'רווח',
  more: '… ועוד {n}',

  'input.sheetName': 'קריאה מהגיליון {name}',
  'input.sheetIndex': 'קריאה מגיליון מספר {n}',
  'input.headerRow': 'הכותרת נמצאת בשורה {n}',
  'input.stopAt': 'עצירת הקריאה בשורה הראשונה שמתחילה ב-{values}',
  'input.readAs.empty': 'בעמודה {col}, {from} נקרא כריק',
  'input.readAs.value': 'בעמודה {col}, {from} נקרא כ-{to}',

  'filter.keep': 'שמירת שורות שבהן {cond}',
  'cond.eq': '{a} שווה ל-{b}',
  'cond.ne': '{a} שונה מ-{b}',
  'cond.gt': '{a} יותר מ-{b}',
  'cond.gte': '{a} לפחות {b}',
  'cond.lt': '{a} פחות מ-{b}',
  'cond.lte': '{a} לכל היותר {b}',
  'cond.isEmpty': '{a} ללא ערך',
  'cond.notEmpty': '{a} עם ערך',
  'cond.oneOf': '{a} שווה לאחד מ-{values}',
  'cond.notOneOf': '{a} שונה מכל אחד מ-{values}',
  'cond.startsWith': 'תחילת {a} היא {b}',
  'cond.endsWith': 'סוף {a} הוא {b}',
  'cond.contains': 'התוכן של {a} כולל {b}',
  'cond.not': 'לא ({c})',
  'cond.andJoin': ' וגם ',
  'cond.orJoin': ' או ',

  'dedupe.same.one': 'שורות עם אותו ערך בעמודה {keys}',
  'dedupe.same.other': 'שורות עם אותם ערכים בעמודות {keys}',
  'dedupe.identical': 'שורות זהות בכל העמודות',
  'dedupe.removeFirst': '{same}: שמירת הראשונה והסרת האחרות',
  'dedupe.removeLast': '{same}: שמירת האחרונה והסרת הקודמות',
  'dedupe.flagFirst': '{same}: שמירת הראשונה וסימון האחרות ככפילויות',
  'dedupe.flagLast': '{same}: שמירת האחרונה וסימון הקודמות ככפילויות',

  'expand.columnsToRows': 'הפיכת העמודות {cols} לשורות נפרדות: שם העמודה נכנס לעמודה {label} והערך לעמודה {value}',
  'expand.skipEmptyCells': 'תאים ריקים מדולגים',
  'expand.customLabels': 'עם התוויות שהגדרתם לשמות העמודות',
  'expand.splitCell': 'פיצול העמודה {col} לפי {sep} לשורות נפרדות: כל חלק נכנס לעמודה {part}',
  'expand.splitIndex': 'מספר החלק נכנס לעמודה {idx}',
  'expand.splitCount': 'מספר החלקים נכנס לעמודה {cnt}',
  'expand.trimmed': 'רווחים סביב כל חלק מוסרים',
  'expand.skipEmptyParts': 'חלקים ריקים מדולגים',
  'expand.fan': 'כל שורה הופכת ל-{count} ({rows})',
  'expand.fanRow': 'שורה {n}: {cells}',
  'expand.fanCell': '{col} = {expr}',
  'made.label': 'שם העמודה',
  'made.value': 'הערך',
  'made.part': 'החלק',
  'made.index': 'מספר החלק',
  'made.count': 'מספר החלקים',
  'expand.labelValue': 'שם העמודה שממנה הגיע הערך ({cols})',
  'expand.valueValue': 'הערך מאותה עמודה',
  'expand.partValue': 'כל חלק של {col}',
  'expand.indexValue': 'מספר החלק',
  'expand.countValue': 'מספר החלקים',
  'expand.fanValue': 'בשורה חדשה {n}: {expr}',

  'col.emptyNeedsInput': 'נשאר ריק (דרוש מידע מכם)',
  'col.missing': 'עמודה שלא קיימת',
  'col.leftEmpty': 'נשאר ריק',
  'col.fixed': 'ערך קבוע {v}',
  'col.translated': 'מתורגם מתוך {src} ({count}; {missing})',
  'col.thenTranslated': 'ואז מתורגם ({count}; {missing})',
  'translate.missingFlag': 'ערכים חדשים מסומנים',
  'translate.missingKeep': 'ערכים חדשים נשארים כפי שהם',
  'mod.padDigits': 'מרופד באפסים ל-{n} ספרות',
  'mod.padChars': 'מרופד ל-{n} תווים באמצעות {c}',
  'mod.dateShown': 'מוצג בתבנית {f}',
  'mod.roundedWhole': 'מעוגל למספר שלם',
  'mod.roundedNearest': 'מעוגל למכפלה הקרובה של {step}',
  'mod.trimmed': 'ללא רווחים מיותרים',
  'mod.upper': 'באותיות גדולות',
  'mod.lower': 'באותיות קטנות',
  'mod.floor': 'מעוגל כלפי מטה למספר שלם',
  'mod.ceil': 'מעוגל כלפי מעלה למספר שלם',
  'mod.asNumber': 'נקרא כמספר',
  'mod.asText': 'כטקסט',
  'mod.asTextFormat': 'כטקסט בתבנית {f}',
  'agg.sum': 'מסוכם לכל {by}',
  'agg.count': 'נספר לכל {by}',
  'agg.min': 'הערך הנמוך ביותר לכל {by}',
  'agg.max': 'הערך הגבוה ביותר לכל {by}',
  'agg.average': 'ממוצע לכל {by}',
  'agg.first': 'הערך הראשון לכל {by}',
  'agg.last': 'הערך האחרון לכל {by}',

  'expr.abs': 'הערך המוחלט של {x}',
  'expr.charsFrom': '{n} תווים מתוך {x}, החל מהתו {p}',
  'expr.charsFromEnd': '{n} תווים מתוך {x}, החל מהתו ה-{p} מהסוף',
  'expr.joinedSep': '{first} מחובר עם {rest}, בהפרדה של {sep}',
  'expr.joined': '{first} מחובר עם {rest}',
  'expr.textOf': 'טקסט המורכב מ-{items}',
  'expr.lookup': '{ret} מהטבלה {table}, לפי {key}',
  'expr.lookupMissing.flag': '(מפתחות חסרים מסומנים)',
  'expr.lookupMissing.empty': '(מפתחות חסרים נשארים ריקים)',
  'expr.lookupMissing.keep': '(מפתחות חסרים נשארים כפי שהם)',
  'expr.if': 'אם {cond} אז {then}, אחרת {else}',
  'expr.case': 'אם {when} אז {then}',
  'expr.otherwise': 'אחרת {else}',
  'expr.coalesce': 'הראשון שאינו ריק מבין {items}',
  'expr.datePart.year': 'השנה של {x}',
  'expr.datePart.month': 'החודש של {x}',
  'expr.datePart.day': 'היום של {x}',
  'expr.dateFormat': '{x} בתבנית {f}',
  'expr.datePlus': '{x} ועוד {amount}',
  'expr.dateMinus': '{x} פחות {amount}',
  'expr.dateDiff': 'מספר ה{unit} בין {a} לבין {b}',
  'unit.days': 'ימים',
  'unit.months': 'חודשים',
  'unit.years': 'שנים',
  'expr.endOfMonth': 'היום האחרון בחודש של {x}',
  'expr.replace': '{x} כשהערך {find} מוחלף ב-{with}',
  'expr.remove': '{x} ללא {find}',
  'expr.split': 'חלק {n} של {x}, לאחר פיצול לפי {sep}',
  'expr.splitLast': 'החלק האחרון של {x}, לאחר פיצול לפי {sep}',
  'expr.splitFromEnd': 'החלק ה-{n} מהסוף של {x}, לאחר פיצול לפי {sep}',
  'expr.length': 'מספר התווים ב-{x}',
  'expr.min': 'הקטן מבין {items}',
  'expr.max': 'הגדול מבין {items}',
  'expr.mod': 'השארית של {a} חלקי {b}',
  'expr.condValue': 'כן אם {cond}, אחרת לא',
  // לאורך שורות (פונקציות החלון): "סכום מצטבר של סכום לכל סוכן, לפי סדר הקובץ"
  'expr.win.runningSum': 'סכום מצטבר של {x}',
  'expr.win.groupSum': 'הסכום של {x}',
  'expr.win.groupAvg': 'הממוצע של {x}',
  'expr.win.groupMin': 'הערך הנמוך ביותר של {x}',
  'expr.win.groupMax': 'הערך הגבוה ביותר של {x}',
  'expr.win.groupCount': 'מספר השורות',
  'expr.win.groupCountOf': 'מספר השורות שיש בהן ערך ב-{x}',
  'expr.win.previous': '{x} מהשורה הקודמת',
  'expr.win.next': '{x} מהשורה הבאה',
  'expr.win.fillDown': 'הערך האחרון של {x} שאינו ריק, מועבר כלפי מטה',
  'expr.win.rowNumber': 'מספר השורה',
  'expr.win.rank': 'דירוג לפי {keys}',
  'win.perGroup': 'לכל {by}',
  'win.allRows': 'בכל השורות',
  'win.fileOrder': 'לפי סדר הקובץ',
  'win.orderBy': 'לפי סדר {keys}',
  'win.then': ', ואז ',
  'win.tiesMin': 'ערכים שווים חולקים דירוג',
  'win.tiesDense': 'ערכים שווים חולקים דירוג, בלי דילוגים',
  'expr.custom': 'חישוב מותאם',

  'title.text': 'כותרת: {text}',
  'title.blank': 'שורה ריקה',
  'title.bold': 'מודגשת',
  'title.max.month': 'החודש של הערך המאוחר ביותר בעמודה {col} ({f})',
  'title.max.year': 'השנה של הערך המאוחר ביותר בעמודה {col} ({f})',
  'title.max.date': 'הערך המאוחר ביותר בעמודה {col} ({f})',
  'title.min.month': 'החודש של הערך המוקדם ביותר בעמודה {col} ({f})',
  'title.min.year': 'השנה של הערך המוקדם ביותר בעמודה {col} ({f})',
  'title.min.date': 'הערך המוקדם ביותר בעמודה {col} ({f})',
  'sort.by': 'מיון לפי {keys}',
  'sort.then': ', ואז ',
  'sort.desc.date': '(מהחדש לישן)',
  'sort.desc.number': '(מהגדול לקטן)',
  'sort.desc.text': '(בסדר אלפביתי הפוך)',
  'sort.desc.plain': '(בסדר יורד)',
  'group.detail': 'קיבוץ שורות לפי {by} (כל השורות מוצגות)',
  'group.summaryOnly': 'שורה אחת לכל {by}; שורות הפירוט לא מוצגות',
  'summary.afterGroup': 'אחרי כל {by}: {row}',
  'summary.atEnd': 'בסוף: {row}',
  'summary.row': 'שורה {label} עם {cells}',
  'summary.rowNoLabel': 'שורה עם {cells}',
  'summary.rowOnlyLabel': 'שורה {label}',
  'summary.rowEmpty': 'שורת סיכום ריקה',
  'summary.bold': 'מודגשת',
  'summary.sum': 'הסכום של {col}',
  'summary.count': 'הספירה של {col}',
  'summary.min': 'המינימום של {col}',
  'summary.max': 'המקסימום של {col}',
  'summary.average': 'הממוצע של {col}',
  'summary.first': 'הערך הראשון של {col}',
  'summary.last': 'הערך האחרון של {col}',
  'file.xlsx': 'קובץ Excel, גיליון {sheet}, {dir}',
  'dir.rtl': 'מימין לשמאל',
  'dir.ltr': 'משמאל לימין',
  'file.kind.comma': 'קובץ טקסט מופרד בפסיקים (CSV)',
  'file.kind.tab': 'קובץ טקסט מופרד בטאבים',
  'file.kind.semicolon': 'קובץ טקסט מופרד בנקודה-פסיק',
  'file.kind.pipe': 'קובץ טקסט מופרד בקו אנכי',
  'file.header': 'עם שורת כותרת',
  'file.noHeader': 'ללא שורת כותרת',
  'file.enc.utf8bom': 'UTF-8 with BOM',
  'file.enc.utf8': 'UTF-8',
  'file.enc.windows1255': 'Windows-1255',
  'file.quote.all': 'כל ערך במרכאות',
  'file.quote.none': 'ללא מרכאות',

  'check.line': 'בדיקה: {rule} ({severity})',
  'check.severity.flag': 'לסמן',
  'check.severity.block': 'להשמיט',
  'check.required': 'הערך בעמודה {col} אינו ריק',
  'check.israeliId': 'הערך בעמודה {col} הוא מספר זהות ישראלי תקין',
  'check.range.both': 'הערך בעמודה {col} הוא בין {min} לבין {max}',
  'check.range.min': 'הערך בעמודה {col} הוא לפחות {min}',
  'check.range.max': 'הערך בעמודה {col} הוא לכל היותר {max}',
  'check.range.none': 'הערך בעמודה {col} הוא מספר',
  'check.oneOf': 'הערך בעמודה {col} הוא אחד מ-{values}',
  'check.unique': 'אין ערכים כפולים בעמודה {col}',
  'check.dateRange': 'הערך בעמודה {col} הוא תאריך בין {from} לבין {to}',
  'check.cutoff.high': 'לפי הדוגמה שלך, הסף בעמודה {col} גבוה מ-{low} ולכל היותר {high}; השתמשנו ב-{value}',
  'check.cutoff.low': 'לפי הדוגמה שלך, הסף בעמודה {col} הוא לפחות {low} ונמוך מ-{high}; השתמשנו ב-{value}',
  'check.cutoff.line': 'בדיקה: {rule}. ערך שביניהם: {severity}',
  'check.sameAs': 'הדוגמה שלך מתאימה גם ל-{other} בעמודה {col}',
  'check.sameAs.line': 'בדיקה: {rule}. שורה שבה הוא נותן ערך אחר: {severity}',

  'table.line': 'טבלה {name}: {count}, חיפוש לפי {key} להחזרת {cols}',
  'table.single': 'טבלה {name}: {count} של {key}',

  'reason.noSource': 'שום דבר עדיין לא ממלא את העמודה הזו. בחרו איך היא נבנית.',
  'reason.dangling': 'העמודה הזו משתמשת במשהו שלא קיים בקובץ הקלט שלכם.',
  'reason.rowsDiffer': 'מספר השורות לא תואם לדוגמה שלכם.',
  'reason.layoutDiffers': 'החלק הזה לא תואם במלואו לדוגמה שלכם.',
  'reason.edited': 'שיניתם את זה.',
  'reason.textFileLayout':
    'לקבצי טקסט בדרך כלל אין שורות כותרת, שורות ריקות או שורות סיכום. בדקו שהמערכת שקוראת את הקובץ מקבלת אותן.',

  'values.one': 'ערך אחד',
  'values.other': '{n} ערכים',
  'rows.one': 'שורה אחת',
  'rows.other': '{n} שורות',
  'entries.one': 'רשומה אחת',
  'entries.other': '{n} רשומות',
  'days.one': 'יום אחד',
  'days.other': '{n} ימים',
  'months.one': 'חודש אחד',
  'months.other': '{n} חודשים',
  'years.one': 'שנה אחת',
  'years.other': '{n} שנים',
  'decimals.one': 'מעוגל לספרה אחת אחרי הנקודה',
  'decimals.other': 'מעוגל ל-{n} ספרות אחרי הנקודה',
  'expr.firstChars.one': 'התו הראשון של {x}',
  'expr.firstChars.other': '{n} התווים הראשונים של {x}',
  'expr.lastChars.one': 'התו האחרון של {x}',
  'expr.lastChars.other': '{n} התווים האחרונים של {x}',
  'blank.after.one': 'השארת שורה ריקה אחת אחרי כל {by}',
  'blank.after.other': 'השארת {n} שורות ריקות אחרי כל {by}',
  'check.length.one': 'הערך בעמודה {col} הוא תו אחד בדיוק',
  'check.length.other': 'הערך בעמודה {col} באורך של {n} תווים בדיוק',
  'reason.mismatch.one': 'שונה מהדוגמה שלכם ב-{n} מתוך {total} שורה.',
  'reason.mismatch.other': 'שונה מהדוגמה שלכם ב-{n} מתוך {total} שורות.',
};

const HEBREW_LETTER = /[א-ת]/;

/** The first letter or digit of an item, to decide between "ו" (before a Hebrew word) and "ו-". */
function startsHebrew(item: readonly Part[]): boolean {
  const flat = item.map((p) => p.text).join('');
  const first = /[\p{L}\p{N}]/u.exec(flat)?.[0] ?? '';
  return HEBREW_LETTER.test(first);
}

function joinList(items: readonly (readonly Part[])[], conj: 'and' | 'or'): Part[] {
  if (items.length <= 1) return joinWith(items, '');
  const head = joinWith(items.slice(0, -1), ', ');
  const last = items[items.length - 1] ?? [];
  const glue = conj === 'or' ? ' או ' : startsHebrew(last) ? ' ו' : ' ו-';
  return joinWith([head, [txt(glue)], last], '');
}

export const heJoiners: Joiners = {
  and: (items) => joinList(items, 'and'),
  or: (items) => joinList(items, 'or'),
};
