// Extracts the verbatim learn-v5 system prompt (LEARN_PROMPT.md section 2, the
// ````text fenced block) and writes it to prompts/learn-v5.txt and to
// src/prompts/learnV5.ts. Never retype the prompt by hand - LEARN_PROMPT.md is
// the single source of truth (see LEARN_PROMPT.md's own header).
//
// Run after any change to that fenced block:
//   pnpm --filter @formatai/api exec tsx ../../packages/shared/scripts/sync-prompt.ts
//   (or: node --experimental-strip-types packages/shared/scripts/sync-prompt.ts)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..', '..');
const specPath = path.join(repoRoot, 'LEARN_PROMPT.md');

/** Extracts the ````text ... ```` fenced system prompt from LEARN_PROMPT.md's markdown. */
export function extractLearnV5Prompt(markdown: string): string {
  const normalized = markdown.replace(/\r\n/g, '\n');
  const match = normalized.match(/````text\n([\s\S]*?)\n````/);
  if (!match) {
    throw new Error('Could not find the ````text fenced system prompt in LEARN_PROMPT.md');
  }
  return `${match[1]}\n`;
}

function main(): void {
  const markdown = readFileSync(specPath, 'utf8');
  const prompt = extractLearnV5Prompt(markdown);

  const txtPath = path.join(here, '..', 'prompts', 'learn-v5.txt');
  writeFileSync(txtPath, prompt, 'utf8');

  const tsPath = path.join(here, '..', 'src', 'prompts', 'learnV5.ts');
  const tsContent =
    '// Generated by scripts/sync-prompt.ts from LEARN_PROMPT.md. Do not edit by hand.\n' +
    `export const LEARN_SYSTEM_PROMPT_V5 = ${JSON.stringify(prompt)};\n`;
  writeFileSync(tsPath, tsContent, 'utf8');

  console.log(`Wrote ${txtPath}`);
  console.log(`Wrote ${tsPath}`);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
