// Extracts the verbatim system prompt of the NEWEST version (LEARN_PROMPT.md section 2, the ````text fenced block - learn-v9) and writes
// it to prompts/learn-v9.txt and to src/prompts/learnV9.ts. Never retype the prompt by hand - LEARN_PROMPT.md is the single source of
// truth (see LEARN_PROMPT.md's own header). learn-v7 is frozen: it is kept for the eval's `--prompt` comparison and never written again -
// prompts/learn-v7.txt (src/prompts/learnV7.ts). Which version every learn sends is `promptVersion` (config/prompts.ts).
//
// learn-v9 (docs/proposals/ai-code-checks.md, owner decision 2026-10-05) is learn-v7 plus ONE section, "# Checking with code": the AI
// step may ask code to check ideas on every row before it answers. The script refuses to write a learn-v9 that is anything else - the
// block with that one section taken out must be the frozen learn-v7 byte for byte (`withoutChecksSection`), so the two can never drift.
//
// Run after any change to that fenced block:
//   pnpm --filter @formatai/api exec tsx ../../packages/shared/scripts/sync-prompt.ts
//   (or: node --experimental-strip-types packages/shared/scripts/sync-prompt.ts)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..', '..');
const specPath = path.join(repoRoot, 'LEARN_PROMPT.md');

/** Extracts the ````text ... ```` fenced system prompt from LEARN_PROMPT.md's markdown. */
export function extractLearnPrompt(markdown: string): string {
  const normalized = markdown.replace(/\r\n/g, '\n');
  const match = normalized.match(/````text\n([\s\S]*?)\n````/);
  if (!match) {
    throw new Error('Could not find the ````text fenced system prompt in LEARN_PROMPT.md');
  }
  return `${match[1]}\n`;
}

/** The heading of learn-v9's one new section. */
export const CHECKS_SECTION_HEADING = '# Checking with code';

/**
 * The prompt without its "Checking with code" section: from that heading's line up to (not including) the next "# " heading. Throws unless
 * the prompt has exactly one such section followed by another heading (a renamed heading must be renamed here too).
 */
export function withoutChecksSection(prompt: string): string {
  const lines = prompt.split('\n');
  const starts = lines.flatMap((line, i) => (line === CHECKS_SECTION_HEADING ? [i] : []));
  if (starts.length !== 1) throw new Error(`Expected exactly one "${CHECKS_SECTION_HEADING}" section in the prompt, found ${starts.length}`);
  const start = starts[0]!;
  const end = lines.findIndex((line, i) => i > start && line.startsWith('# '));
  if (end < 0) throw new Error(`The "${CHECKS_SECTION_HEADING}" section must be followed by another section`);
  lines.splice(start, end - start);
  return lines.join('\n');
}

function main(): void {
  const markdown = readFileSync(specPath, 'utf8');
  const prompt = extractLearnPrompt(markdown);

  // learn-v9 = learn-v7 + one section, exactly.
  const v7 = readFileSync(path.join(here, '..', 'prompts', 'learn-v7.txt'), 'utf8').replace(/\r\n/g, '\n');
  if (withoutChecksSection(prompt) !== v7) {
    throw new Error(`LEARN_PROMPT.md section 2 must be learn-v7 plus the "${CHECKS_SECTION_HEADING}" section and nothing else (learn-v9)`);
  }

  const txtPath = path.join(here, '..', 'prompts', 'learn-v9.txt');
  writeFileSync(txtPath, prompt, 'utf8');

  const tsPath = path.join(here, '..', 'src', 'prompts', 'learnV9.ts');
  const tsContent =
    '// Generated by scripts/sync-prompt.ts from LEARN_PROMPT.md. Do not edit by hand.\n' +
    '// learn-v9 = learn-v7 + the "Checking with code" section (docs/proposals/ai-code-checks.md).\n' +
    `export const LEARN_SYSTEM_PROMPT_V9 = ${JSON.stringify(prompt)};\n`;
  writeFileSync(tsPath, tsContent, 'utf8');

  console.log(`Wrote ${txtPath}`);
  console.log(`Wrote ${tsPath}`);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
